# Generated by Django 5.2 on 2025-05-04 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_pge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_links', to='search_app.page')),
                ('target_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_links', to='search_app.page')),
            ],
        ),
    ]
