# Generated by Django 5.2 on 2025-05-04 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0006_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
