# Generated by Django 5.2 on 2025-05-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0008_pagelink'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagelink',
            unique_together=set(),
        ),
    ]
