# Generated by Django 5.2 on 2025-05-05 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0010_page_outgoing_links_delete_pagelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='outgoing_links',
        ),
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='search_app.page')),
                ('to_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='search_app.page')),
            ],
        ),
    ]
