# Generated by Django 5.2.1 on 2025-05-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0013_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
